#!/usr/bin/env python3
"""Generate CODEBASE_MAP.md from voro_mcp/ using the ast module.

Walks every .py file under voro_mcp/, extracts classes, methods, standalone
functions, and internal imports. Outputs grouped-by-package Markdown.
"""

import ast
import subprocess
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "voro_mcp"
OUTPUT = REPO_ROOT / "docs" / "CODEBASE_MAP.md"


def source_revision() -> str:
    """Return the latest committed voro_mcp/ revision, or unknown if unavailable.

    Use ``--full-history`` so merge-parent ordering does not change the emitted
    revision between a branch head and GitHub's pull-request merge ref.
    """
    try:
        return subprocess.check_output(
            ["git", "log", "--full-history", "-1", "--format=%h", "--", "voro_mcp"],
            cwd=REPO_ROOT,
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def parse_file(filepath: Path) -> dict:
    """Parse a single Python file and extract structural info."""
    rel = filepath.relative_to(REPO_ROOT)
    source = filepath.read_text(encoding="utf-8", errors="replace")
    line_count = source.count("\n") + (1 if source and not source.endswith("\n") else 0)

    try:
        tree = ast.parse(source, filename=str(rel))
    except SyntaxError:
        return {"path": str(rel), "lines": line_count, "classes": [], "functions": [], "imports": []}

    classes = []
    functions = []
    imports = []

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            methods = [
                n.name for n in ast.iter_child_nodes(node)
                if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
                and not (n.name.startswith("__") and n.name.endswith("__"))
            ]
            classes.append({"name": node.name, "methods": methods})

        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.append(node.name)

        elif isinstance(node, ast.ImportFrom):
            if node.module and node.module.startswith("voro_mcp"):
                names = [alias.name for alias in node.names]
                imports.append(f"from {node.module} import {', '.join(names)}")

    return {
        "path": str(rel),
        "lines": line_count,
        "classes": classes,
        "functions": functions,
        "imports": imports,
    }


def collect_files() -> list[Path]:
    """Collect all .py files under voro_mcp/, sorted."""
    return sorted(SRC_DIR.rglob("*.py"))


def group_by_package(entries: list[dict]) -> dict[str, list[dict]]:
    """Group parsed entries by their parent package directory."""
    groups = defaultdict(list)
    for entry in entries:
        parts = Path(entry["path"]).parts
        # Package is everything up to but not including the filename
        pkg = "/".join(parts[:-1]) if len(parts) > 1 else "voro_mcp"
        groups[pkg].append(entry)
    return dict(sorted(groups.items()))


def render_markdown(groups: dict[str, list[dict]]) -> str:
    """Render the grouped entries as Markdown."""
    lines = [
        "# Codebase Map",
        "",
        "> Auto-generated by `scripts/generate_codebase_map.py`. Do not edit manually.",
        "",
        "# Status: ACTIVE",
        "# Class: generated-reference",
        "# Authority: machine-generated",
        "# Generator: scripts/generate_codebase_map.py",
        f"# Source Revision: {source_revision()}",
        "",
    ]

    total_files = sum(len(entries) for entries in groups.values())
    total_lines = sum(e["lines"] for entries in groups.values() for e in entries)
    lines.append(f"**{total_files} files, {total_lines:,} lines**")
    lines.append("")

    for pkg, entries in groups.items():
        lines.append(f"## {pkg}/")
        lines.append("")

        for entry in entries:
            filename = Path(entry["path"]).name
            lines.append(f"### `{entry['path']}` ({entry['lines']} lines)")
            lines.append("")

            if entry["classes"]:
                for cls in entry["classes"]:
                    if cls["methods"]:
                        methods_str = ", ".join(f"`{m}`" for m in cls["methods"])
                        lines.append(f"- **class {cls['name']}**: {methods_str}")
                    else:
                        lines.append(f"- **class {cls['name']}**")

            if entry["functions"]:
                for fn in entry["functions"]:
                    lines.append(f"- `{fn}()`")

            if entry["imports"]:
                lines.append("")
                lines.append("Internal imports:")
                for imp in entry["imports"]:
                    lines.append(f"- `{imp}`")

            # Skip empty __init__.py files (no classes, functions, or imports)
            if not entry["classes"] and not entry["functions"] and not entry["imports"]:
                # Replace the ### header with a simpler line
                lines[-1] = f"- `{filename}` ({entry['lines']} lines) — empty"
                lines.pop(-2)  # remove the blank line

            lines.append("")

    return "\n".join(lines)


def main():
    files = collect_files()
    entries = [parse_file(f) for f in files]
    groups = group_by_package(entries)
    md = render_markdown(groups)
    OUTPUT.write_text(md, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(entries)} files)")


if __name__ == "__main__":
    main()
